name: Test

on: [push, pull_request]

jobs:
  style-check:
    name: Linux ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check style
      run: cargo fmt -- --check

  linux:
    name: Linux ubuntu-latest
    runs-on: ubuntu-latest
    needs: [style-check]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run example
      run: cargo run --verbose --example info

  windows:
    name: Windows ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [style-check]
    strategy:
      matrix:
        os: [windows-2019, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run example
      run: cargo run --verbose --example info

  macos:
    name: macOS-latest
    runs-on: macOS-latest
    needs: [style-check]
    steps:
    - uses: actions/checkout@v1
    - name: Get Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup && sh ./rustup -y
    - name: Build
      run: source ~/.cargo/env; cargo build --verbose
    - name: Run example
      run: source ~/.cargo/env; cargo run --verbose --example info
